import type { NextPage } from "next";
import Head from "next/head";
import profilePic from "../public/images/me.jpg";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="bg-">
      <Head>
        <title>Mark Jed Bibat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto max-w-4xl px-6 sm:px-8 mt-20 mb-36">
        <div className="flex mb-10 gap-5">
          <div className="mt-6 max-w-xl sm:my-0">
            <h1 className="mb-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">
              Mark Jed Bibat
            </h1>
            <h2 className="mb-4 text-gray-300">Backend/Full Stack Develepor</h2>
            <p className="w-full font-normal leading-7 text-gray-400 sm:max-w-sm md:max-w-xl">
              Welcome to my portfolio. I am a graduate student in Bachelor of
              science in information technology at University of Pangasinan. In
              my free time I enjoy making websites and experimenting with web
              app technologies.
            </p>
          </div>
          <div className="block w-40">
            <Image
              className="rounded-full"
              src={profilePic}
              alt="Picture of the author"
              placeholder="blur"
              objectFit="cover"
              layout="responsive"
            />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
