import type { NextPage } from "next";
import Head from "next/head";
import profilePic from "../public/images/me.jpg";
import Image from "next/image";
import technologies from "../constants/techonologies";
import Technologies from "../components/Technologies";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Mark Jed Bibat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto max-w-3xl px-6 sm:px-8 mt-20 mb-36">
        <div className="mb-14 sm:flex sm:items-center sm:justify-between">
          <div className="mt-6 max-w-lg sm:my-0">
            <h1 className="mb-2 text-3xl font-bold text-white sm:text-4xl">
              Mark Jed Bibat
            </h1>
            <h2 className="mb-4 text-gray-100">Backend/Full Stack Developer</h2>
            <p className="w-full font-normal leading-7  text-gray-300 sm:max-w-sm md:max-w-lg">
              Welcome to my portfolio. I'm a web developer wherein I specialize
              in backend development but can work on frontend aswell. In my free
              time I enjoy exploring web technologies and also I'm a big fan of
              Esports!
            </p>
          </div>
        </div>

        {/* TECHONOLOGIES */}
        <div>
          <h2 className="mb-6 text-2xl font-bold text-white">
            Technologies I use:
          </h2>

          <div className="grid grid-cols-3 gap-4">
            {" "}
            {technologies.map(({ id, ...rest }) => (
              <Technologies key={id} {...rest} />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
